# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Beer')),
                ('beer2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Beer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, max_length=10)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Beer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
