# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_graph_like_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
