# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171102_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'verbose_name': 'Beer', 'verbose_name_plural': 'Beer'},
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
