# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171102_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name_lower',
            field=models.TextField(default=''),
        ),
    ]
