# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_beer_name_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name_lower',
            field=models.CharField(default='', max_length=100),
        ),
    ]
