# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171104_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='beer_id',
            new_name='beer',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='score',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='user_id',
            new_name='user',
        ),
    ]
